In [ ]:
import os

In [ ]:
print(os.listdir("C:/Users/Afza/Desktop/Urdu/data"))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'alif', 'alif mad aa', 'ayn', 'baa', 'bari yaa', 'cheey', 'choti yaa', 'daal', 'dhaal', 'faa', 'gaaf', 'ghain', 'haa1', 'haa2', 'haa3', 'hamza', 'jeem', 'kaaf', 'khaa', 'laam', 'meem', 'noon', 'noonghunna', 'paa', 'qaaf', 'raa', 'rhraa', 'seen', 'seey', 'sheen', 'swaad', 'taa', 'ttaa', 'twa', 'waw', 'zaaa', 'zaal', 'zhaa', 'zwaa', 'zwaad']


In [ ]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras import layers
import pickle
import cv2 as cv

In [ ]:
DIRECTORY = r'C:/Users/Afza/Desktop/Urdu/data'
CATEGORIES = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'alif', 'alif mad aa', 'ayn', 'baa', 'bari yaa', 'cheey', 'choti yaa', 'daal', 'dhaal', 'faa', 'gaaf', 'ghain', 'haa1', 'haa2', 'haa3', 'hamza', 'jeem', 'kaaf', 'khaa', 'laam', 'meem', 'noon', 'noonghunna', 'paa', 'qaaf', 'raa', 'rhraa', 'seen', 'seey', 'sheen', 'swaad', 'taa', 'ttaa', 'twa', 'waw', 'zaaa', 'zaal', 'zhaa', 'zwaa', 'zwaad']

In [ ]:
IMG_SIZE = 28

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    label = CATEGORIES.index(category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        img_arr = cv.imread(img_path)
        img_arr = cv.resize(img_arr, (IMG_SIZE, IMG_SIZE))
        data.append([img_arr, label])

In [ ]:
len(data)

34934

In [ ]:
data

[[array([[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         ...,
  
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
  
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]], dtype=uint8),
  0],
 [array([[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 

In [ ]:
import random
random.shuffle(data)

In [ ]:
X = []
y = []

for features, label in data:
    X.append(features)
    y.append(label)

In [ ]:
X = np.array(X)
y = np.array(y)

In [ ]:
X

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        ...,

        [[ 0,  0,  0],
         [32, 32, 32],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [21, 21, 21],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 2,  2,  2],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0, 

In [ ]:
y

array([37, 48, 22, ..., 18, 23, 11])

In [ ]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))

In [ ]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [ ]:
len(X)

34934

In [ ]:
X

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        ...,

        [[ 0,  0,  0],
         [32, 32, 32],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [21, 21, 21],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 2,  2,  2],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0, 

In [ ]:
y

array([37, 48, 22, ..., 18, 23, 11])

In [ ]:
X = X/255

In [ ]:
X

array([[[[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]],

        [[0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ],
         [0.        , 0.        , 0.        ]],

        ...,

        [[0.        , 0.        , 0.        ],
         [0.1254902 , 0.1254902 , 0.1254902 ]

In [ ]:
X.shape

(34934, 28, 28, 3)

In [ ]:
# now design CNN Model
model = tf.keras.models.Sequential([# Convolutional layer 1
                                    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(28, 28, 3)),
                                    tf.keras.layers.MaxPooling2D(2, 2),

                                    # Convolutional layer 2
                                    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2, 2),

                                    # Flatten layer - Output of convolution
                                    tf.keras.layers.Flatten(),

                                    # Hidden layer
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),

                                    # Output layer
                                    tf.keras.layers.Dense(50, activation=tf.nn.softmax)])

In [ ]:
model.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 64)        1792      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 1600)              0         
                                                                 
 dense (Dense)               (None, 128)               2

In [ ]:
history = model.fit(X, y, epochs=10)

Epoch 1/10
1092/1092 [==============================] - 85s 73ms/step - loss: 0.8706 - accuracy: 0.7379
Epoch 2/10
1092/1092 [==============================] - 75s 69ms/step - loss: 0.3213 - accuracy: 0.8950
Epoch 3/10
1092/1092 [==============================] - 73s 67ms/step - loss: 0.2095 - accuracy: 0.9306
Epoch 4/10
1092/1092 [==============================] - 72s 66ms/step - loss: 0.1533 - accuracy: 0.9475
Epoch 5/10
1092/1092 [==============================] - 72s 66ms/step - loss: 0.1161 - accuracy: 0.9580
Epoch 6/10
1092/1092 [==============================] - 73s 67ms/step - loss: 0.0912 - accuracy: 0.9665
Epoch 7/10
1092/1092 [==============================] - 73s 67ms/step - loss: 0.0750 - accuracy: 0.9724
Epoch 8/10
1092/1092 [==============================] - 72s 66ms/step - loss: 0.0621 - accuracy: 0.9764
Epoch 9/10
1092/1092 [==============================] - 73s 67ms/step - loss: 0.0565 - accuracy: 0.9788
Epoch 10/10
1092/1092 [==============================] - 75s 69m

In [ ]:
scores = model.evaluate(X, y)

1092/1092 [==============================] - 24s 21ms/step - loss: 0.0515 - accuracy: 0.9803


In [ ]:
model.save("model.h5")

In [ ]:
CATEGORIES = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'alif', 'alif mad aa', 'ayn', 'baa', 'bari yaa', 'cheey', 'choti yaa', 'daal', 'dhaal', 'faa', 'gaaf', 'ghain', 'haa1', 'haa2', 'haa3', 'hamza', 'jeem', 'kaaf', 'khaa', 'laam', 'meem', 'noon', 'noonghunna', 'paa', 'qaaf', 'raa', 'rhraa', 'seen', 'seey', 'sheen', 'swaad', 'taa', 'ttaa', 'twa', 'waw', 'zaaa', 'zaal', 'zhaa', 'zwaa', 'zwaad']

def image(path):
    img = cv.imread(path)
    new_arr = cv.resize(img, (28, 28))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(1, 28, 28, 3)
    return new_arr

model = tf.keras.models.load_model('model.h5')

In [ ]:
prediction = model.predict([image('alif (1).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 43ms/step
7


In [ ]:
prediction = model.predict([image('5 (2).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 139ms/step
5


In [ ]:
prediction = model.predict([image('alifmad (2).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 48ms/step
alif mad aa


In [ ]:
prediction = model.predict([image('faa (5).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 53ms/step
faa


In [ ]:
prediction = model.predict([image('7 (3).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 52ms/step
7


In [ ]:
prediction = model.predict([image('zwaad (3).jpg')])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 52ms/step
zwaad


In [ ]:
import numpy as np
from skimage.feature import hog
from skimage import data, exposure
import matplotlib.pyplot as plt

# Load a sample image
image = data.astronaut()

# Calculate the HOG features
fd, hog_image = hog(image, orientations=8, pixels_per_cell=(16, 16),
                    cells_per_block=(1, 1), visualize=True, multichannel=True)

# Reshape the HOG features for visualization
hog_features_2d = fd.reshape((fd.shape[0], 1))

# Display the 2D HOG
plt.figure(figsize=(10, 5))
plt.bar(range(len(hog_features_2d)), hog_features_2d[:, 0], color='green')
plt.xlabel('Feature Index')
plt.ylabel('HOG Value')
plt.title('HOG for Urdu Handwritten Digits and Chracters')
plt.show()


In [ ]:
import cv2
from skimage import feature
import matplotlib.pyplot as plt

# Load your custom image (replace 'your_image_path.jpg' with the actual path)
image_path = '/content/drive/MyDrive/Datasets/urdu hand/BAy.JPG'
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Calculate LBP
radius = 1
n_points = 8 * radius
lbp_image = feature.local_binary_pattern(image, n_points, radius, method='uniform')

# Display the original image and LBP
fig, axes = plt.subplots(1, 2, figsize=(10, 5))
ax = axes.ravel()

ax[0].imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
ax[0].set_title('Original Image')

ax[1].imshow(lbp_image, cmap=plt.cm.nipy_spectral)
ax[1].set_title('Local Binary Pattern')
plt.show()


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Assuming you have a 2D numpy array 'confusion_matrix' representing the confusion matrix
# Rows and columns correspond to true and predicted labels, respectively

# Create a sample confusion matrix (replace this with your actual confusion matrix)
confusion_matrix = np.array([[50, 5, 0],
                             [3, 45, 2],
                             [0, 1, 48]])

# Define class labels (replace with your actual class labels)
class_labels = ['Urdu Handwritten Digits',  'Urdu Handwritten chracters', 'Single Chracter']

# Create a figure and a set of subplots
fig, ax = plt.subplots(figsize=(8, 6))

# Create an image of the confusion matrix
cax = ax.matshow(confusion_matrix, cmap='Greens')

# Add colorbar legend
fig.colorbar(cax)

# Set labels for axes
plt.xticks(np.arange(len(class_labels)), class_labels)
plt.yticks(np.arange(len(class_labels)), class_labels)

# Display the confusion matrix values (optional)
for i in range(len(class_labels)):
    for j in range(len(class_labels)):
        text = ax.text(j, i, confusion_matrix[i, j], ha='center', va='center', color='black')

# Set labels for axes
ax.set_xlabel('Detected')
ax.set_ylabel('True')
plt.title('Confusion Matrix')

# Display the plot
plt.show()


In [ ]:
import matplotlib.pyplot as plt

# Define the F1 score
f1_score = 88.6

# Create a bar chart
plt.figure(figsize=(8, 6))
plt.bar(['F1 Score'], [f1_score], color='y')
plt.ylim(0, 100)  # Set the y-axis limits to 0-100 for percentage
plt.xlabel('Metric')
plt.ylabel('Score (%)')
plt.title('F1 Score')
plt.text(0, f1_score + 2, f'{f1_score:.1f}%', ha='center', va='bottom', fontsize=12, color='green')
plt.show()


In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Define the recall score
recall_score = 0.75

# Create a figure
fig = plt.figure()

# Add 3D Axes
ax = fig.add_subplot(111, projection='3d')

# Define the position of the bar
xpos = 1
ypos = 1

# Define the height of the bar
zpos = 0
dx = dy = 0.1
dz = recall_score

# Create the 3D bar
ax.bar3d(xpos, ypos, zpos, dx, dy, dz, color='red')

# Set labels
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Recall Score')

# Set title
plt.title('Recall Score')

# Show the plot
plt.show()


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!apt-get install -y git
!git config --global user.email "atirrazasyed@gmail.com"
!git config --global user.name "atirrazasyed1"

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.


In [ ]:
%cd "/content/drive/My Drive/Your_Code_Folder"